export const CREATE_STUDENT = 'CREATE_STUDENT';
export const DETAIL_STUDENTS = 'DETAIL_STUDENTS';
export const UPDATE_STUDENT = 'UPDATE_STUDENT';
export const DELETE_STUDENT = 'DELETE_STUDENT';
export const GET_LIST_STUDENT = 'GET_LIST_STUDENT';

export const CREATE_CLASS = 'CREATE_CLASS';
export const DETAIL_CLASS = 'DETAIL_CLASS';
export const UPDATE_CLASS = 'UPDATE_CLASS';
export const DELETE_CLASS = 'DELETE_CLASS';
export const GET_LIST_CLASS = 'GET_LIST_CLASS';

export const LOADING = 'LOADING';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';
export const RESET_STORE = 'RESET_STORE';
