const routes = {
  adminDashboard: "/adminDashboard",
  home: "/",
  productDetail: "/product-detail/:id",
  studentList: "/students",
  classList: "/classes",
  classDetail: "/class-detail/:id",
  newStudent: "/new-student",
  newClass: "/new-class",
  editClass: "/edit-class/:id",
  login: "/login",
  registration: "/registration",
  productListMng: "/product-management",
  newProduct: "/new-product",
  editProduct: "/edit-product/:id",
  order: "/order",
  aboutUs: "/about",
  newCategory: "/new-category",
  categories: "/categories",
  userManagement: "/user-management",
  categoryEditWith: "/category-edit",
  categoryEdit: "/category-edit/:id",
  blogsManagement: "/blogs-management",
  blogs: "/blogs",
  blogDetails: "/blog/:id",
};

export default routes;
