const routes = {
  adminDashboard: "/adminDashboard",
  home: "/home",
  products: "/products",
  productDetail: "/products/:id",
  productDetailWith: "/products/",
  login: "/login",
  registration: "/registration",
  productListMng: "/product-management",
  newProduct: "/new-product",
  editProduct: "/edit-product/:id",
  orders: "/orders",
  aboutUs: "/about",
  newCategory: "/new-category",
  categories: "/categories",
  userManagement: "/user-management",
  categoryEditWith: "/category-edit",
  categoryEdit: "/category-edit/:id",
  blogsManagement: "/blogs-management",
  blogs: "/blogs",
  blogDetails: "/blogs/:id",
  newBlog: "/blogs/new-blog",
  blogEditWith: "/blogs/edit/",
  editBlog: "/blogs/edit/:id",
};

export default routes;
